catalog:
  "@libsql/client": ^0.15.15
  "@octokit/webhooks": ^14.1.3
  "@octokit/webhooks-types": ^7.6.1
  typescript: ^5.9.3
  dotenv: ^17.2.3
  drizzle-orm: ^0.44.6
  octokit: ^5.0.3
  drizzle-kit: ^0.31.5

packages:
  - packages/*

ignoredBuiltDependencies:
  - sharp

injectWorkspacePackages: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - "@studiocms/*"
  - "@withstudiocms/*"

syncInjectedDepsAfterScripts:
  - build
