catalog:
  "@libsql/client": ^0.18.0
  "@octokit/webhooks": ^14.2.0
  "@octokit/webhooks-types": ^7.6.1
  typescript: ^5.9.3
  dotenv: ^17.4.2
  drizzle-orm: ^0.45.2
  octokit: ^5.0.5
  drizzle-kit: ^0.31.10

packages:
  - packages/*

ignoredBuiltDependencies:
  - sharp

injectWorkspacePackages: true

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - studiocms
  - "@studiocms/*"
  - "@withstudiocms/*"

syncInjectedDepsAfterScripts:
  - build
