name: Docker Build and Deploy
description: Build and push a Docker image to GitHub Container Registry and Dokploy.

inputs:
  GITHUB_ACTOR:
    description: "GitHub Actor"
    required: true
  GITHUB_TOKEN:
    description: "GitHub Token for authentication"
    required: true
  GITHUB_REPOSITORY:
    description: "GitHub Repository name"
    required: true
  GITHUB_SHA:
    description: "GitHub Commit SHA"
    required: true
  GITHUB_REF_NAME:
    description: "GitHub Reference Name"
    required: true
  DOCKERFILE:
    description: "Path to the Dockerfile"
    required: true
  IMAGE_NAME:
    description: "Name of the Docker image"
    required: true
  DOKPLOY_API_URL:
    description: "Dokploy API URL"
    required: true
  DOKPLOY_API_KEY:
    description: "Dokploy API Key"
    required: true
  DOKPLOY_COMPOSE_ID:
    description: "Dokploy Compose ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up QEMU (for multi-arch)
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

    - name: Cache pnpm store
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
      with:
        registry: ghcr.io
        username: ${{ inputs.GITHUB_ACTOR }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
      with:
        context: .
        file: ${{ inputs.DOCKERFILE }}
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ inputs.GITHUB_REPOSITORY }}-${{ inputs.IMAGE_NAME }}:latest
          ghcr.io/${{ inputs.GITHUB_REPOSITORY }}-${{ inputs.IMAGE_NAME }}:${{ inputs.GITHUB_SHA }}
          ghcr.io/${{ inputs.GITHUB_REPOSITORY }}-${{ inputs.IMAGE_NAME }}:${{ inputs.GITHUB_REF_NAME }}
        cache-from: type=registry,ref=ghcr.io/${{ inputs.GITHUB_REPOSITORY }}-${{ inputs.IMAGE_NAME }}:cache
        cache-to: type=inline

    - name: Verify pushed image
      shell: bash
      run: |
        echo "Pushed: ghcr.io/${{ inputs.GITHUB_REPOSITORY }}-${{ inputs.IMAGE_NAME }}:latest"
        echo "Pushed: ghcr.io/${{ inputs.GITHUB_REPOSITORY }}-${{ inputs.IMAGE_NAME }}:${{ inputs.GITHUB_SHA }}"
        echo "Pushed: ghcr.io/${{ inputs.GITHUB_REPOSITORY }}-${{ inputs.IMAGE_NAME }}:${{ inputs.GITHUB_REF_NAME }}"

    - name: Deploy to Dokploy Compose
      uses: withstudiocms/automations/.github/actions/deploy-dokploy-compose@c2dfd186eab9d163cbd535984b82cda1ff8e4689 # main
      with:
        api_url: ${{ inputs.DOKPLOY_API_URL }}
        api_key: ${{ inputs.DOKPLOY_API_KEY }}
        compose_id: ${{ inputs.DOKPLOY_COMPOSE_ID }}
        image: ghcr.io/${{ inputs.GITHUB_REPOSITORY }}-${{ inputs.IMAGE_NAME }}:${{ inputs.GITHUB_SHA }}
