name: Docker Build and Deploy
description: Build and push a Docker image to GitHub Container Registry and Dokploy.

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token for authentication"
    required: true
  DOCKERFILE:
    description: "Path to the Dockerfile"
    required: true
  IMAGE_NAME:
    description: "Name of the Docker image"
    required: true
  DOKPLOY_API_URL:
    description: "Dokploy API URL"
    required: true
  DOKPLOY_API_KEY:
    description: "Dokploy API Key"
    required: true
  DOKPLOY_COMPOSE_ID:
    description: "Dokploy Compose ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up QEMU (for multi-arch)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache pnpm store
      uses: actions/cache@v4
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.DOCKERFILE }}
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}-${{ inputs.IMAGE_NAME }}:latest
          ghcr.io/${{ github.repository }}-${{ inputs.IMAGE_NAME }}:${{ github.sha }}
          ghcr.io/${{ github.repository }}-${{ inputs.IMAGE_NAME }}:${{ github.ref_name }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}-${{ inputs.IMAGE_NAME }}:cache
        cache-to: type=inline

    - name: Verify pushed image
      shell: bash
      run: |
        echo "Pushed: ghcr.io/${{ github.repository }}-${{ inputs.IMAGE_NAME }}:latest"
        echo "Pushed: ghcr.io/${{ github.repository }}-${{ inputs.IMAGE_NAME }}:${{ github.sha }}"
        echo "Pushed: ghcr.io/${{ github.repository }}-${{ inputs.IMAGE_NAME }}:${{ github.ref_name }}"

    - name: Deploy to Dokploy Compose
      uses: withstudiocms/automations/.github/actions/deploy-dokploy-compose@b488fa91598547478e170a4742916293a91a4410 # main
      with:
        api_url: ${{ inputs.DOKPLOY_API_URL }}
        api_key: ${{ inputs.DOKPLOY_API_KEY }}
        compose_id: ${{ inputs.DOKPLOY_COMPOSE_ID }}
        image: ghcr.io/${{ github.repository }}-${{ inputs.IMAGE_NAME }}:${{ github.sha }}
